### PR TITLE
Added lookups like startswith, endswith, istartswith, iendswith in filter like Django

### PR DESCRIPTION
**Pull request by saurabhgharatpara**

### CODE REVIEW

**Comment by tarsil** [comment]
@saurabhgharatpara this is a great contribution and I'm more than happy with what you presented and we can merge if all passes. 

Have a look at https://mongoz.tarsild.io/contributing/

This shows you how to run the tests and run the lints which is basically "hatch run lint".

Make sure this is covered and then we can give it a go? 

Thank you for this

**Comment by saurabhgharatpara** [comment]
Yes ive run the lint also added testcases and fixed the missing import

**Comment by tarsil** [comment]
@saurabhgharatpara failing the tests

**Review by tarsil — APPROVED** [review]

**Comment by tarsil** [comment]
@saurabhgharatpara congratulations! We needed to release and this was also included in the newest version 0.10.7 👏🏼

**Pull request merged**
