### PR TITLE
Add the multi-tenancy for the indexes handling

### PR DESCRIPTION
**Pull request by harshalizode**
Add the multi-tenancy for the indexes handling
Update the create_many method to the create documents for the selected database at run time.

### CODE REVIEW

**Comment by tarsil** [comment]
@harshalizode thank you for this but a few things are missing:

1. CI is failing because you havent rnu the lint in your machine and in the docs tells you how to setup your local development. Here: https://mongoz.dymmond.com/contributing/#development
2. Rebase from the main branch as the support for Python 3.8 was removed.
3. Tests are missing. We cannot merge this without tests proving this is actually working as intended. Proper testing.

Once this is addressed then we can review and if merged we will release the version 0.11.0

**Comment by tarsil** [comment]
@harshalizode ?

**Comment by harshalizode** [comment]
I don't understand why the test case failed while mearging the code.
model_to_test
drop_index
Here, we've included the year's index to the AnotherMovie model and its meta. Why is the test case failing when we have three indices in total—_id, unique email, and year?

**Comment by tarsil** [comment]
@harshalizode this is the reason https://github.com/dymmond/mongoz/actions/runs/12366722249/job/34513879097?pr=64

Has nothing to do with merging the code

**Comment by harshalizode** [comment]
> Here, we've included the year's index to the AnotherMovie model and its meta. Why is the test case failing when we have three indices in total—_id, unique email, and year?

We have the three indices, what is the duplicate here, please assist to pass it.

**Comment by tarsil** [comment]
@harshalizode it's hard to assist to pass. The tests must be properly executed. We can't hack testing. Did you see the error? That is the error. You are asserting it's 3 but in fact it's 2. So something is not right in the code and your PR?

**Comment by tarsil** [comment]
@harshalizode most likely you will need to prepare the dB in advance and make it clean like here 

https://github.com/dymmond/mongoz/blob/main/tests/indexes/test_unique.py#L24

**Comment by harshalizode** [comment]
> @harshalizode most likely you will need to prepare the dB in advance and make it clean like here
> 
> https://github.com/dymmond/mongoz/blob/main/tests/indexes/test_unique.py#L24
> 
> Of course, applied to your tests and documents.
> 
> Or maybe your code is not doing what is supposed to.

Something is wrong, after prepare the database then also giving the same assertion.

**Review by tarsil — APPROVED** [review]

**Pull request merged**
